version: '2'

services:
# Ref.: https://hub.docker.com/_/mysql/
  wamp7-mysql:
    container_name: wamp-mysql5.7
#This will result in an image named lamp and tagged tag
    image: mysql:5.7
#Expose ports. Either specify both ports (HOST:CONTAINER), or just the container port (a random host port will be chosen).
    ports:
      - "4407:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysqld:/run/mysqld

  wamp7-php:
# Ref.: https://hub.docker.com/_/php/
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wamp-php
    image: php:php7-apache
    ports:
      - "8000:80"
    # environment:
    #   - GUARD_DIR=/var/www/html/wp-content/themes/museeum
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - wamp7-mysql
